include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    use_setters_to_change_properties: false
    public_member_api_docs: false
    file_names: false